Traceback (most recent call last):
  File "C:\Users\Ian\IdeaProjects\PokemonRedExperiments\baselines\run_baseline_parallel_fast.py", line 117, in <module>
    main()
  File "C:\Users\Ian\IdeaProjects\PokemonRedExperiments\baselines\run_baseline_parallel_fast.py", line 112, in main
    model.learn(total_timesteps=5_000_000, callback=callback)  # Train the model
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ian\AppData\Local\Programs\Python\Python311\Lib\site-packages\stable_baselines3\ppo\ppo.py", line 308, in learn
    return super().learn(
           ^^^^^^^^^^^^^^
  File "C:\Users\Ian\AppData\Local\Programs\Python\Python311\Lib\site-packages\stable_baselines3\common\on_policy_algorithm.py", line 259, in learn
    continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ian\AppData\Local\Programs\Python\Python311\Lib\site-packages\stable_baselines3\common\on_policy_algorithm.py", line 154, in collect_rollouts
    rollout_buffer.reset()
  File "C:\Users\Ian\AppData\Local\Programs\Python\Python311\Lib\site-packages\stable_baselines3\common\buffers.py", line 364, in reset
    self.observations = np.zeros((self.buffer_size, self.n_envs, *self.obs_shape), dtype=np.float32)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 11.2 GiB for an array with shape (16384, 12, 3, 128, 40) and data type float32